version: "3.8"
services:
  DoR:
    container_name: DoR
    image: analogcyan/dns-over-rng:latest
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - SHODAN_API_KEY=${SHODAN_API_KEY}
    volumes:
      - ./cache:/app/cache
